{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "Person": "Ida B. Wells", "Unique_ID": "BA1", "Section": "2", "Section2": "2", "Address": "Carrubers Close Mission, 65 High Street", "Address_fo": "65 High Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Ida B. Wells", "ID": "d12" }, "geometry": { "type": "Point", "coordinates": [ -3.1855659, 55.9506209, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Frederick J. Loudin", "Unique_ID": "BA2", "Section": "2", "Section2": "2", "Address": "Carrubers Close Mission, 65 High Street", "Address_fo": "65 High Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Frederick J. Loudin", "ID": "d7" }, "geometry": { "type": "Point", "coordinates": [ -3.1855659, 55.9506209, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Jesse Ewing Glasgow Jr.", "Unique_ID": "BA3", "Section": "2", "Section2": "2", "Address": "10 Hill Place", "Address_fo": "10 Hill Place", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Jesse Ewing Glasgow Jr.", "ID": "d5" }, "geometry": { "type": "Point", "coordinates": [ -3.1835243, 55.9463746, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Sarah Remond", "Unique_ID": "BA4", "Section": "2", "Section2": "2", "Address": "Brighton Street Church, Brighton Street", "Address_fo": "Brighton Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Sarah Remond", "ID": "d8" }, "geometry": { "type": "Point", "coordinates": [ -3.1895933729, 55.9466128068, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Ida B. Wells", "Unique_ID": "BA5", "Section": "2", "Section2": "2", "Address": "National Bible Society, 4-5 St. Andrew Square", "Address_fo": "4-5 St. Andrew Square", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Ida B. Wells", "ID": "d13" }, "geometry": { "type": "Point", "coordinates": [ -3.1929994291, 55.9533902786, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "William Wells Brown and William Craft", "Unique_ID": "BA6", "Section": "2", "Section2": "2", "Address": "Edinburgh Total Abstinence Society, 52 Nicolson Street", "Address_fo": "52 Nicolson Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "William Wells Brown and William Craft", "ID": "d2" }, "geometry": { "type": "Point", "coordinates": [ -3.1845047, 55.9456922, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Josiah Henson", "Unique_ID": "BA7", "Section": "2", "Section2": "2", "Address": "27 Brunton Road (London Road)", "Address_fo": "27 London Road", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Josiah Henson", "ID": "d6" }, "geometry": { "type": "Point", "coordinates": [ -3.1723252096, 55.9578597711, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "William Wells Brown and William Craft", "Unique_ID": "BA8", "Section": "2", "Section2": "2", "Address": "Old Infirmary, Infirmary Street", "Address_fo": "Infirmary Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "William Wells Brown and William Craft", "ID": "d3" }, "geometry": { "type": "Point", "coordinates": [ -3.1838, 55.9487, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Ira Aldridge", "Unique_ID": "BA9", "Section": "2", "Section2": "2", "Address": "Adelphi Theatre, 1 Little King Street", "Address_fo": "1 Little King Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Ira Aldridge", "ID": "d1" }, "geometry": { "type": "Point", "coordinates": [ -3.1875096052, 55.9560060346, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Ignatius Sancho", "Unique_ID": "BA10", "Section": "2", "Section2": "2", "Address": "8 Queen Street", "Address_fo": "8 Queen Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Ignatius Sancho", "ID": "d9" }, "geometry": { "type": "Point", "coordinates": [ -3.1962275552, 55.9550094333, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Samuel Ringgold Ward", "Unique_ID": "BA11", "Section": "2", "Section2": "2", "Address": "Albany Street Chapel, 24a Broughton Street", "Address_fo": "24a Broughton Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Samuel Ringgold Ward", "ID": "d11" }, "geometry": { "type": "Point", "coordinates": [ -3.1889092524, 55.9574379906, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Amanda Smith", "Unique_ID": "BA12", "Section": "2", "Section2": "2", "Address": "John Knox House, 43-45 High Street", "Address_fo": "43-45 High Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Amanda Smith", "ID": "d10" }, "geometry": { "type": "Point", "coordinates": [ -3.1849572841, 55.9506904827, 0.0 ] } },
{ "type": "Feature", "properties": { "Person": "Ellen Craft and William Craft", "Unique_ID": "BA13", "Section": "2", "Section2": "2", "Address": "Cannon's Hotel, 11 South St. Andrew Street", "Address_fo": "11 South St. Andrew Street", "Town": "Edinburgh", "State": "United Kingdom", "Person2": "Ellen Craft and William Craft", "ID": "d4" }, "geometry": { "type": "Point", "coordinates": [ -3.1913084738, 55.9534667438, 0.0 ] } }
]
}
